# Run tests with Travis CI

language: python
dist: trusty

python:
  - 3.6

before_install:
  - export DJANGO_SETTINGS_MODULE=backend.settings_test
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt

script:
  - python manage.py test -v2

cache:
  directories:
    - $HOME/.cache/pip
