# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

      - image: postgres:latest
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password

      - image: rabbitmq:3.5.4

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: "Setup environment"
          command: |
            python3 -m venv venv
            echo 'export DJANGO_SETTINGS_MODULE="backend.settings_test"' >> $BASH_ENV
            echo "source venv/bin/activate" >> $BASH_ENV

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt
            pip install coverage codecov

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: Run celery worker
          command: |
            celery -A backend worker -l info
          background: true

      - run:
          name: Run Tests
          command: |
            coverage run manage.py test -v2
            codecov

      - run:
          name: Lint
          command: |
            flake8
            pylint_runner
