# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4

      - image: postgres:latest
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password

      - image: rabbitmq:3.5.4

      - image: radialapps/sonic:v1.2.1

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: "Setup environment"
          command: |
            echo 'export PIPENV_VENV_IN_PROJECT=true' >> $BASH_ENV
            echo 'export DJANGO_SETTINGS_MODULE="backend.settings_test_full"' >> $BASH_ENV

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Pipfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install Dependencies
          command: |
            pipenv install
            sudo pip install coverage codecov

      - save_cache:
          paths:
            - ./.venv
          key: v1-dependencies-{{ checksum "Pipfile.lock" }}

      - run:
          name: Run celery worker
          command: |
            pipenv run celery -A backend worker -l info
          background: true

      - run:
          name: Run Tests
          command: |
            pipenv run coverage run manage.py test -v2
            pipenv run codecov

      - run:
          name: Lint
          command: |
            pipenv run flake8
            pipenv run pylint_runner
